export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'fr', name: 'Français' },
  { code: 'ar', name: 'العربية' },
  { code: 'de', name: 'Deutsch' },
  { code: 'it', name: 'Italiano' },
  { code: 'es', name: 'Español' },
  { code: 'pt', name: 'Português' },
  { code: 'hi', name: 'हिन्दी' },
];

export const DICTIONARY = {
  'Fruits & Vegetables': [
    { en: 'Apple', fr: 'Pomme', ar: 'تفاحة', de: 'Apfel', it: 'Mela', es: 'Manzana', pt: 'Maçã', hi: 'सेब' },
    { en: 'Banana', fr: 'Banane', ar: 'موز', de: 'Banane', it: 'Banana', es: 'Plátano', pt: 'Banana', hi: 'केला' },
    { en: 'Carrot', fr: 'Carotte', ar: 'جزر', de: 'Karotte', it: 'Carota', es: 'Zanahoria', pt: 'Cenoura', hi: 'गाजर' },
    { en: 'Potato', fr: 'Pomme de terre', ar: 'بطاطس', de: 'Kartoffel', it: 'Patata', es: 'Patata', pt: 'Batata', hi: 'आलू' },
    { en: 'Tomato', fr: 'Tomate', ar: 'طماطم', de: 'Tomate', it: 'Pomodoro', es: 'Tomate', pt: 'Tomate', hi: 'टमाटर' },
    { en: 'Orange', fr: 'Orange', ar: 'برتقال', de: 'Orange', it: 'Arancia', es: 'Naranja', pt: 'Laranja', hi: 'संतरा' },
    { en: 'Strawberry', fr: 'Fraise', ar: 'فراولة', de: 'Erdbeere', it: 'Fragola', es: 'Fresa', pt: 'Morango', hi: 'स्ट्रॉबेरी' },
    { en: 'Grapes', fr: 'Raisins', ar: 'عنب', de: 'Trauben', it: 'Uva', es: 'Uvas', pt: 'Uvas', hi: 'अंगूर' },
    { en: 'Watermelon', fr: 'Pastèque', ar: 'بطيخ', de: 'Wassermelone', it: 'Anguria', es: 'Sandía', pt: 'Melancia', hi: 'तरबूज' },
    { en: 'Lemon', fr: 'Citron', ar: 'ليمون', de: 'Zitrone', it: 'Limone', es: 'Limón', pt: 'Limão', hi: 'नींबू' },
    { en: 'Onion', fr: 'Oignon', ar: 'بصل', de: 'Zwiebel', it: 'Cipolla', es: 'Cebolla', pt: 'Cebola', hi: 'प्याज' },
    { en: 'Garlic', fr: 'Ail', ar: 'ثوم', de: 'Knoblauch', it: 'Aglio', es: 'Ajo', pt: 'Alho', hi: 'लहसुन' },
    { en: 'Cucumber', fr: 'Concombre', ar: 'خيار', de: 'Gurke', it: 'Cetriolo', es: 'Pepino', pt: 'Pepino', hi: 'खीरा' },
    { en: 'Pepper', fr: 'Poivron', ar: 'فلفل', de: 'Paprika', it: 'Peperone', es: 'Pimiento', pt: 'Pimentão', hi: 'शिमला मिर्च' },
    { en: 'Broccoli', fr: 'Brocoli', ar: 'بروكلي', de: 'Brokkoli', it: 'Broccoli', es: 'Brócoli', pt: 'Brócolis', hi: 'ब्रोकोली' },
    { en: 'Corn', fr: 'Maïs', ar: 'ذرة', de: 'Mais', it: 'Mais', es: 'Maíz', pt: 'Milho', hi: 'मक्का' },
    { en: 'Mushroom', fr: 'Champignon', ar: 'فطر', de: 'Pilz', it: 'Fungo', es: 'Champiñón', pt: 'Cogumelo', hi: 'मशरूम' },
    { en: 'Pineapple', fr: 'Ananas', ar: 'أناناس', de: 'Ananas', it: 'Ananas', es: 'Piña', pt: 'Abacaxi', hi: 'अनानास' },
    { en: 'Mango', fr: 'Mangue', ar: 'مانجو', de: 'Mango', it: 'Mango', es: 'Mango', pt: 'Manga', hi: 'आम' },
    { en: 'Peach', fr: 'Pêche', ar: 'خوخ', de: 'Pfirsich', it: 'Pesca', es: 'Melocotón', pt: 'Pêssego', hi: 'आड़ू' }
  ],
  'Animals': [
    { en: 'Lion', fr: 'Lion', ar: 'أسد', de: 'Löwe', it: 'Leone', es: 'León', pt: 'Leão', hi: 'शेर' },
    { en: 'Elephant', fr: 'Éléphant', ar: 'فيل', de: 'Elefant', it: 'Elefante', es: 'Elefante', pt: 'Elefante', hi: 'हाथी' },
    { en: 'Dog', fr: 'Chien', ar: 'كلب', de: 'Hund', it: 'Cane', es: 'Perro', pt: 'Cachorro', hi: 'कुत्ता' },
    { en: 'Cat', fr: 'Chat', ar: 'قطة', de: 'Katze', it: 'Gatto', es: 'Gato', pt: 'Gato', hi: 'बिल्ली' },
    { en: 'Bird', fr: 'Oiseau', ar: 'طائر', de: 'Vogel', it: 'Uccello', es: 'Pájaro', pt: 'Pássaro', hi: 'पक्षी' },
    { en: 'Tiger', fr: 'Tigre', ar: 'نمر', de: 'Tiger', it: 'Tigre', es: 'Tigre', pt: 'Tigre', hi: 'बाघ' },
    { en: 'Bear', fr: 'Ours', ar: 'دب', de: 'Bär', it: 'Orso', es: 'Oso', pt: 'Urso', hi: 'भालू' },
    { en: 'Monkey', fr: 'Singe', ar: 'قرد', de: 'Affe', it: 'Scimmia', es: 'Mono', pt: 'Macaco', hi: 'बंदर' },
    { en: 'Horse', fr: 'Cheval', ar: 'حصان', de: 'Pferd', it: 'Cavallo', es: 'Caballo', pt: 'Cavalo', hi: 'घोड़ा' },
    { en: 'Cow', fr: 'Vache', ar: 'بقرة', de: 'Kuh', it: 'Mucca', es: 'Vaca', pt: 'Vaca', hi: 'गाय' },
    { en: 'Pig', fr: 'Cochon', ar: 'خنزير', de: 'Schwein', it: 'Maiale', es: 'Cerdo', pt: 'Porco', hi: 'सुअर' },
    { en: 'Sheep', fr: 'Mouton', ar: 'خروف', de: 'Schaf', it: 'Pecora', es: 'Oveja', pt: 'Ovelha', hi: 'भेड़' },
    { en: 'Chicken', fr: 'Poulet', ar: 'دجاجة', de: 'Huhn', it: 'Pollo', es: 'Pollo', pt: 'Galinha', hi: 'मुर्गी' },
    { en: 'Duck', fr: 'Canard', ar: 'بطة', de: 'Ente', it: 'Anatra', es: 'Pato', pt: 'Pato', hi: 'बतख' },
    { en: 'Fish', fr: 'Poisson', ar: 'سمكة', de: 'Fisch', it: 'Pesce', es: 'Pez', pt: 'Peixe', hi: 'मछली' },
    { en: 'Shark', fr: 'Requin', ar: 'قرش', de: 'Hai', it: 'Squalo', es: 'Tiburón', pt: 'Tubarão', hi: 'शार्क' },
    { en: 'Whale', fr: 'Baleine', ar: 'حوت', de: 'Wal', it: 'Balena', es: 'Ballena', pt: 'Baleia', hi: 'व्हेल' },
    { en: 'Snake', fr: 'Serpent', ar: 'ثعبان', de: 'Schlange', it: 'Serpente', es: 'Serpiente', pt: 'Cobra', hi: 'सांप' },
    { en: 'Frog', fr: 'Grenouille', ar: 'ضفدع', de: 'Frosch', it: 'Rana', es: 'Rana', pt: 'Sapo', hi: 'मेंढक' },
    { en: 'Spider', fr: 'Araignée', ar: 'عنكبوت', de: 'Spinne', it: 'Ragno', es: 'Araña', pt: 'Aranha', hi: 'मकड़ी' }
  ],
  'Clothes': [
    { en: 'Shirt', fr: 'Chemise', ar: 'قميص', de: 'Hemd', it: 'Camicia', es: 'Camisa', pt: 'Camisa', hi: 'कमीज़' },
    { en: 'Pants', fr: 'Pantalon', ar: 'سروال', de: 'Hose', it: 'Pantaloni', es: 'Pantalones', pt: 'Calças', hi: 'पतलून' },
    { en: 'Shoes', fr: 'Chaussures', ar: 'حذاء', de: 'Schuhe', it: 'Scarpe', es: 'Zapatos', pt: 'Sapatos', hi: 'जूते' },
    { en: 'Hat', fr: 'Chapeau', ar: 'قبعة', de: 'Hut', it: 'Cappello', es: 'Sombrero', pt: 'Chapéu', hi: 'टोपी' },
    { en: 'Jacket', fr: 'Veste', ar: 'سترة', de: 'Jacke', it: 'Giacca', es: 'Chaqueta', pt: 'Jaqueta', hi: 'जैकेट' },
    { en: 'Socks', fr: 'Chaussettes', ar: 'جوارب', de: 'Socken', it: 'Calzini', es: 'Calcetines', pt: 'Meias', hi: 'मोज़े' },
    { en: 'Dress', fr: 'Robe', ar: 'فستان', de: 'Kleid', it: 'Vestito', es: 'Vestido', pt: 'Vestido', hi: 'पोशाक' },
    { en: 'Skirt', fr: 'Jupe', ar: 'تنورة', de: 'Rock', it: 'Gonna', es: 'Falda', pt: 'Saia', hi: 'स्कर्ट' },
    { en: 'Shorts', fr: 'Short', ar: 'شورت', de: 'Shorts', it: 'Pantaloncini', es: 'Pantalones cortos', pt: 'Shorts', hi: 'शॉर्ट्स' },
    { en: 'Sweater', fr: 'Pull', ar: 'سترة صوفية', de: 'Pullover', it: 'Maglione', es: 'Suéter', pt: 'Suéter', hi: 'स्वेटर' },
    { en: 'Coat', fr: 'Manteau', ar: 'معطف', de: 'Mantel', it: 'Cappotto', es: 'Abrigo', pt: 'Casaco', hi: 'कोट' },
    { en: 'Scarf', fr: 'Écharpe', ar: 'وشاح', de: 'Schal', it: 'Sciarpa', es: 'Bufanda', pt: 'Cachecol', hi: 'स्कार्फ' },
    { en: 'Gloves', fr: 'Gants', ar: 'قفازات', de: 'Handschuhe', it: 'Guanti', es: 'Guantes', pt: 'Luvas', hi: 'दस्ताने' },
    { en: 'Belt', fr: 'Ceinture', ar: 'حزام', de: 'Gürtel', it: 'Cintura', es: 'Cinturón', pt: 'Cinto', hi: 'बेल्ट' },
    { en: 'Tie', fr: 'Cravate', ar: 'ربطة عنق', de: 'Krawatte', it: 'Cravatta', es: 'Corbata', pt: 'Gravata', hi: 'टाई' },
    { en: 'Underwear', fr: 'Sous-vêtements', ar: 'ملابس داخلية', de: 'Unterwäsche', it: 'Biancheria intima', es: 'Ropa interior', pt: 'Roupa íntima', hi: 'अंडरवियर' },
    { en: 'Boots', fr: 'Bottes', ar: 'أحذية طويلة', de: 'Stiefel', it: 'Stivali', es: 'Botas', pt: 'Botas', hi: 'जूते' },
    { en: 'Sandals', fr: 'Sandales', ar: 'صنادل', de: 'Sandalen', it: 'Sandali', es: 'Sandalias', pt: 'Sandálias', hi: 'सैंडल' },
    { en: 'Slippers', fr: 'Chaussons', ar: 'نعال', de: 'Hausschuhe', it: 'Pantofole', es: 'Zapatillas', pt: 'Chinelos', hi: 'चप्पल' },
    { en: 'Pajamas', fr: 'Pyjama', ar: 'بيجاما', de: 'Schlafanzug', it: 'Pigiama', es: 'Pijama', pt: 'Pijama', hi: 'पजामा' }
  ],
  'Home Objects': [
    { en: 'Chair', fr: 'Chaise', ar: 'كرسي', de: 'Stuhl', it: 'Sedia', es: 'Silla', pt: 'Cadeira', hi: 'कुर्सी' },
    { en: 'Table', fr: 'Table', ar: 'طاولة', de: 'Tisch', it: 'Tavolo', es: 'Mesa', pt: 'Mesa', hi: 'मेज' },
    { en: 'Bed', fr: 'Lit', ar: 'سرير', de: 'Bett', it: 'Letto', es: 'Cama', pt: 'Cama', hi: 'बिस्तर' },
    { en: 'Television', fr: 'Télévision', ar: 'تلفزيون', de: 'Fernseher', it: 'Televisione', es: 'Televisión', pt: 'Televisão', hi: 'टेलीविज़न' },
    { en: 'Lamp', fr: 'Lampe', ar: 'مصباح', de: 'Lampe', it: 'Lampada', es: 'Lámpara', pt: 'Lâmpada', hi: 'दीपक' },
    { en: 'Sofa', fr: 'Canapé', ar: 'أريكة', de: 'Sofa', it: 'Divano', es: 'Sofá', pt: 'Sofá', hi: 'सोफ़ा' },
    { en: 'Door', fr: 'Porte', ar: 'باب', de: 'Tür', it: 'Porta', es: 'Puerta', pt: 'Porta', hi: 'दरवाज़ा' },
    { en: 'Window', fr: 'Fenêtre', ar: 'نافذة', de: 'Fenster', it: 'Finestra', es: 'Ventana', pt: 'Janela', hi: 'खिड़की' },
    { en: 'Clock', fr: 'Horloge', ar: 'ساعة', de: 'Uhr', it: 'Orologio', es: 'Reloj', pt: 'Relógio', hi: 'घड़ी' },
    { en: 'Mirror', fr: 'Miroir', ar: 'مرآة', de: 'Spiegel', it: 'Specchio', es: 'Espejo', pt: 'Espelho', hi: 'दर्पण' },
    { en: 'Fridge', fr: 'Réfrigérateur', ar: 'ثلاجة', de: 'Kühlschrank', it: 'Frigorifero', es: 'Refrigerador', pt: 'Geladeira', hi: 'फ्रिज' },
    { en: 'Oven', fr: 'Four', ar: 'فرن', de: 'Ofen', it: 'Forno', es: 'Horno', pt: 'Forno', hi: 'ओवन' },
    { en: 'Microwave', fr: 'Micro-ondes', ar: 'ميكروويف', de: 'Mikrowelle', it: 'Microonde', es: 'Microondas', pt: 'Micro-ondas', hi: 'माइक्रोवेव' },
    { en: 'Washing Machine', fr: 'Machine à laver', ar: 'غسالة', de: 'Waschmaschine', it: 'Lavatrice', es: 'Lavadora', pt: 'Máquina de lavar', hi: 'वाशिंग मशीन' },
    { en: 'Toilet', fr: 'Toilettes', ar: 'مرحاض', de: 'Toilette', it: 'Gabinetto', es: 'Inodoro', pt: 'Vaso sanitário', hi: 'शौचालय' },
    { en: 'Shower', fr: 'Douche', ar: 'دش', de: 'Dusche', it: 'Doccia', es: 'Ducha', pt: 'Chuveiro', hi: 'शावर' },
    { en: 'Sink', fr: 'Évier', ar: 'حوض', de: 'Spülbecken', it: 'Lavandino', es: 'Fregadero', pt: 'Pia', hi: 'सिंक' },
    { en: 'Carpet', fr: 'Tapis', ar: 'سجادة', de: 'Teppich', it: 'Tappeto', es: 'Alfombra', pt: 'Tapete', hi: 'कालीन' },
    { en: 'Curtain', fr: 'Rideau', ar: 'ستارة', de: 'Vorhang', it: 'Tenda', es: 'Cortina', pt: 'Cortina', hi: 'पर्दा' },
    { en: 'Bookshelf', fr: 'Étagère', ar: 'رف كتب', de: 'Bücherregal', it: 'Libreria', es: 'Estantería', pt: 'Estante', hi: 'किताबों की अलमारी' }
  ],
  'Movies': [
    { en: 'Inception', fr: 'Inception', ar: 'استهلال', de: 'Inception', it: 'Inception', es: 'Origen', pt: 'A Origem', hi: 'इंसेप्शन' },
    { en: 'Titanic', fr: 'Titanic', ar: 'تيتانيك', de: 'Titanic', it: 'Titanic', es: 'Titanic', pt: 'Titanic', hi: 'टाइटैनिक' },
    { en: 'Avatar', fr: 'Avatar', ar: 'أفاتار', de: 'Avatar', it: 'Avatar', es: 'Avatar', pt: 'Avatar', hi: 'अवतार' },
    { en: 'The Matrix', fr: 'Matrix', ar: 'الماتريكس', de: 'Matrix', it: 'Matrix', es: 'Matrix', pt: 'Matrix', hi: 'द मैट्रिक्स' },
    { en: 'Gladiator', fr: 'Gladiator', ar: 'المصارع', de: 'Gladiator', it: 'Gladiatore', es: 'Gladiator', pt: 'Gladiador', hi: 'ग्लैडिएटर' },
    { en: 'The Godfather', fr: 'Le Parrain', ar: 'العراب', de: 'Der Pate', it: 'Il Padrino', es: 'El Padrino', pt: 'O Poderoso Chefão', hi: 'द गॉडफादर' },
    { en: 'Jurassic Park', fr: 'Jurassic Park', ar: 'الحديقة الجوراسية', de: 'Jurassic Park', it: 'Jurassic Park', es: 'Parque Jurásico', pt: 'Jurassic Park', hi: 'जुरासिक पार्क' },
    { en: 'Star Wars', fr: 'Star Wars', ar: 'حرب النجوم', de: 'Star Wars', it: 'Star Wars', es: 'Star Wars', pt: 'Star Wars', hi: 'स्टार वार्स' },
    { en: 'Harry Potter', fr: 'Harry Potter', ar: 'هاري بوتر', de: 'Harry Potter', it: 'Harry Potter', es: 'Harry Potter', pt: 'Harry Potter', hi: 'हैरी पॉटर' },
    { en: 'Lord of the Rings', fr: 'Le Seigneur des anneaux', ar: 'سيد الخواتم', de: 'Herr der Ringe', it: 'Il Signore degli Anelli', es: 'El Señor de los Anillos', pt: 'O Senhor dos Anéis', hi: 'लॉर्ड ऑफ द रिंग्स' },
    { en: 'Avengers', fr: 'Avengers', ar: 'المنتقمون', de: 'Avengers', it: 'Avengers', es: 'Vengadores', pt: 'Vingadores', hi: 'एवेंजर्स' },
    { en: 'Spider-Man', fr: 'Spider-Man', ar: 'الرجل العنكبوت', de: 'Spider-Man', it: 'Spider-Man', es: 'Spider-Man', pt: 'Homem-Aranha', hi: 'स्पाइडर-मैन' },
    { en: 'Batman', fr: 'Batman', ar: 'باتمان', de: 'Batman', it: 'Batman', es: 'Batman', pt: 'Batman', hi: 'बैटमैन' },
    { en: 'Toy Story', fr: 'Toy Story', ar: 'قصة لعبة', de: 'Toy Story', it: 'Toy Story', es: 'Toy Story', pt: 'Toy Story', hi: 'टॉय स्टोरी' },
    { en: 'Finding Nemo', fr: 'Le Monde de Nemo', ar: 'البحث عن نيمو', de: 'Findet Nemo', it: 'Alla ricerca di Nemo', es: 'Buscando a Nemo', pt: 'Procurando Nemo', hi: 'फाइंडिंग निमो' },
    { en: 'The Lion King', fr: 'Le Roi Lion', ar: 'الأسد الملك', de: 'Der König der Löwen', it: 'Il Re Leone', es: 'El Rey León', pt: 'O Rei Leão', hi: 'द लायन किंग' },
    { en: 'Frozen', fr: 'La Reine des neiges', ar: 'ملكة الثلج', de: 'Die Eiskönigin', it: 'Frozen', es: 'Frozen', pt: 'Frozen', hi: 'फ्रोजन' },
    { en: 'Shrek', fr: 'Shrek', ar: 'شريك', de: 'Shrek', it: 'Shrek', es: 'Shrek', pt: 'Shrek', hi: 'श्रेक' },
    { en: 'Home Alone', fr: 'Maman, j\'ai raté l\'avion', ar: 'وحدي في المنزل', de: 'Kevin - Allein zu Haus', it: 'Mamma, ho perso l\'aereo', es: 'Solo en casa', pt: 'Esqueceram de Mim', hi: 'होम अलोन' },
    { en: 'Jaws', fr: 'Les Dents de la mer', ar: 'الفك المفترس', de: 'Der weiße Hai', it: 'Lo squalo', es: 'Tiburón', pt: 'Tubarão', hi: 'जॉज़' }
  ],
  'Countries': [
    { en: 'Brazil', fr: 'Brésil', ar: 'البرازيل', de: 'Brasilien', it: 'Brasile', es: 'Brasil', pt: 'Brasil', hi: 'ब्राज़ील' },
    { en: 'Japan', fr: 'Japon', ar: 'اليابان', de: 'Japan', it: 'Giappone', es: 'Japón', pt: 'Japão', hi: 'जापान' },
    { en: 'France', fr: 'France', ar: 'فرنسا', de: 'Frankreich', it: 'Francia', es: 'Francia', pt: 'França', hi: 'फ़्रांस' },
    { en: 'Egypt', fr: 'Égypte', ar: 'مصر', de: 'Ägypten', it: 'Egitto', es: 'Egipto', pt: 'Egito', hi: 'मिस्र' },
    { en: 'Canada', fr: 'Canada', ar: 'كندا', de: 'Kanada', it: 'Canada', es: 'Canadá', pt: 'Canadá', hi: 'कनाडा' },
    { en: 'USA', fr: 'États-Unis', ar: 'الولايات المتحدة', de: 'USA', it: 'Stati Uniti', es: 'EE. UU.', pt: 'EUA', hi: 'अमेरिका' },
    { en: 'China', fr: 'Chine', ar: 'الصين', de: 'China', it: 'Cina', es: 'China', pt: 'China', hi: 'चीन' },
    { en: 'India', fr: 'Inde', ar: 'الهند', de: 'Indien', it: 'India', es: 'India', pt: 'Índia', hi: 'भारत' },
    { en: 'Australia', fr: 'Australie', ar: 'أستراليا', de: 'Australien', it: 'Australia', es: 'Australia', pt: 'Austrália', hi: 'ऑस्ट्रेलिया' },
    { en: 'Germany', fr: 'Allemagne', ar: 'ألمانيا', de: 'Deutschland', it: 'Germania', es: 'Alemania', pt: 'Alemanha', hi: 'जर्मनी' },
    { en: 'Italy', fr: 'Italie', ar: 'إيطاليا', de: 'Italien', it: 'Italia', es: 'Italia', pt: 'Itália', hi: 'इटली' },
    { en: 'Spain', fr: 'Espagne', ar: 'إسبانيا', de: 'Spanien', it: 'Spagna', es: 'España', pt: 'Espanha', hi: 'स्पेन' },
    { en: 'Mexico', fr: 'Mexique', ar: 'المكسيك', de: 'Mexiko', it: 'Messico', es: 'México', pt: 'México', hi: 'मेक्सिको' },
    { en: 'Argentina', fr: 'Argentine', ar: 'الأرجنتين', de: 'Argentinien', it: 'Argentina', es: 'Argentina', pt: 'Argentina', hi: 'अर्जेंटीना' },
    { en: 'Russia', fr: 'Russie', ar: 'روسيا', de: 'Russland', it: 'Russia', es: 'Rusia', pt: 'Rússia', hi: 'रूस' },
    { en: 'South Africa', fr: 'Afrique du Sud', ar: 'جنوب أفريقيا', de: 'Südafrika', it: 'Sudafrica', es: 'Sudáfrica', pt: 'África do Sul', hi: 'दक्षिण अफ्रीका' },
    { en: 'South Korea', fr: 'Corée du Sud', ar: 'كوريا الجنوبية', de: 'Südkorea', it: 'Corea del Sud', es: 'Corea del Sur', pt: 'Coreia do Sul', hi: 'दक्षिण कोरिया' },
    { en: 'Turkey', fr: 'Turquie', ar: 'تركيا', de: 'Türkei', it: 'Turchia', es: 'Turquía', pt: 'Turquia', hi: 'तुर्की' },
    { en: 'Saudi Arabia', fr: 'Arabie Saoudite', ar: 'السعودية', de: 'Saudi-Arabien', it: 'Arabia Saudita', es: 'Arabia Saudita', pt: 'Arábia Saudita', hi: 'सऊदी अरब' },
    { en: 'United Kingdom', fr: 'Royaume-Uni', ar: 'المملكة المتحدة', de: 'Großbritannien', it: 'Regno Unito', es: 'Reino Unido', pt: 'Reino Unido', hi: 'यूनाइटेड किंगडम' }
  ]
};

export const CATEGORY_QUESTIONS: Record<string, Record<string, string>[]> = {
  'Fruits & Vegetables': [
    { en: 'Is it usually eaten raw or cooked?', fr: 'Se mange-t-il généralement cru ou cuit ?', ar: 'هل يؤكل عادة نيئًا أم مطبوخًا؟', de: 'Wird es normalerweise roh oder gekocht gegessen?', it: 'Si mangia di solito crudo o cotto?', es: '¿Se come normalmente crudo o cocido?', pt: 'Geralmente é comido cru ou cozido?', hi: 'क्या इसे आमतौर पर कच्चा या पकाकर खाया जाता है?' },
    { en: 'What color is it on the outside?', fr: 'De quelle couleur est-il à l\'extérieur ?', ar: 'ما هو لونه من الخارج؟', de: 'Welche Farbe hat es außen?', it: 'Di che colore è all\'esterno?', es: '¿De qué color es por fuera?', pt: 'Qual é a cor por fora?', hi: 'यह बाहर से किस रंग का है?' },
    { en: 'Is it sweet or savory?', fr: 'Est-ce sucré ou salé ?', ar: 'هل هو حلو أم مالح؟', de: 'Ist es süß oder herzhaft?', it: 'È dolce o salato?', es: '¿Es dulce o salado?', pt: 'É doce ou salgado?', hi: 'क्या यह मीठा है या नमकीन?' },
    { en: 'Do you peel it before eating?', fr: 'Le pelez-vous avant de le manger ?', ar: 'هل تقشره قبل الأكل؟', de: 'Schält man es vor dem Essen?', it: 'Lo sbucci prima di mangiarlo?', es: '¿Lo pelas antes de comerlo?', pt: 'Você descasca antes de comer?', hi: 'क्या आप खाने से पहले इसे छीलते हैं?' },
    { en: 'Where does it usually grow (tree, ground, vine)?', fr: 'Où pousse-t-il généralement (arbre, sol, vigne) ?', ar: 'أين ينمو عادة (شجرة، أرض، كرمة)؟', de: 'Wo wächst es normalerweise (Baum, Boden, Ranke)?', it: 'Dove cresce di solito (albero, terra, vite)?', es: '¿Dónde crece normalmente (árbol, suelo, enredadera)?', pt: 'Onde geralmente cresce (árvore, chão, videira)?', hi: 'यह आमतौर पर कहाँ उगता है (पेड़, ज़मीन, बेल)?' }
  ],
  'Animals': [
    { en: 'How many legs does it have?', fr: 'Combien de pattes a-t-il ?', ar: 'كم عدد أرجله؟', de: 'Wie viele Beine hat es?', it: 'Quante zampe ha?', es: '¿Cuántas patas tiene?', pt: 'Quantas pernas tem?', hi: 'इसके कितने पैर हैं?' },
    { en: 'Where does it live (land, water, air)?', fr: 'Où vit-il (terre, eau, air) ?', ar: 'أين يعيش (يابسة، ماء، هواء)؟', de: 'Wo lebt es (Land, Wasser, Luft)?', it: 'Dove vive (terra, acqua, aria)?', es: '¿Dónde vive (tierra, agua, aire)?', pt: 'Onde vive (terra, água, ar)?', hi: 'यह कहाँ रहता है (ज़मीन, पानी, हवा)?' },
    { en: 'Is it kept as a pet?', fr: 'Est-il gardé comme animal de compagnie ?', ar: 'هل يتم تربيته كحيوان أليف؟', de: 'Wird es als Haustier gehalten?', it: 'È tenuto come animale domestico?', es: '¿Se tiene como mascota?', pt: 'É mantido como animal de estimação?', hi: 'क्या इसे पालतू जानवर के रूप में रखा जाता है?' },
    { en: 'What does it usually eat?', fr: 'Que mange-t-il généralement ?', ar: 'ماذا يأكل عادة؟', de: 'Was frisst es normalerweise?', it: 'Cosa mangia di solito?', es: '¿Qué come normalmente?', pt: 'O que geralmente come?', hi: 'यह आमतौर पर क्या खाता है?' },
    { en: 'Is it bigger or smaller than a human?', fr: 'Est-il plus grand ou plus petit qu\'un humain ?', ar: 'هل هو أكبر أم أصغر من الإنسان؟', de: 'Ist es größer oder kleiner als ein Mensch?', it: 'È più grande o più piccolo di un essere umano?', es: '¿Es más grande o más pequeño que un humano?', pt: 'É maior ou menor que um humano?', hi: 'क्या यह इंसान से बड़ा है या छोटा?' }
  ],
  'Clothes': [
    { en: 'Which part of the body does it cover?', fr: 'Quelle partie du corps couvre-t-il ?', ar: 'أي جزء من الجسم يغطي؟', de: 'Welchen Körperteil bedeckt es?', it: 'Quale parte del corpo copre?', es: '¿Qué parte del cuerpo cubre?', pt: 'Qual parte do corpo cobre?', hi: 'यह शरीर के किस हिस्से को ढकता है?' },
    { en: 'When do you usually wear it (season/occasion)?', fr: 'Quand le portez-vous généralement (saison/occasion) ?', ar: 'متى ترتديه عادة (موسم/مناسبة)؟', de: 'Wann trägt man es normalerweise (Jahreszeit/Anlass)?', it: 'Quando lo indossi di solito (stagione/occasione)?', es: '¿Cuándo lo usas normalmente (temporada/ocasión)?', pt: 'Quando você geralmente usa (estação/ocasião)?', hi: 'आप इसे आमतौर पर कब पहनते हैं (मौसम/अवसर)?' },
    { en: 'Is it worn by men, women, or both?', fr: 'Est-il porté par des hommes, des femmes ou les deux ?', ar: 'هل يرتديه الرجال أم النساء أم كلاهما؟', de: 'Wird es von Männern, Frauen oder beiden getragen?', it: 'È indossato da uomini, donne o entrambi?', es: '¿Lo usan hombres, mujeres o ambos?', pt: 'É usado por homens, mulheres ou ambos?', hi: 'क्या इसे पुरुष, महिलाएँ या दोनों पहनते हैं?' },
    { en: 'What material is it usually made of?', fr: 'De quel matériau est-il généralement fait ?', ar: 'من أي مادة يصنع عادة؟', de: 'Aus welchem Material besteht es normalerweise?', it: 'Di che materiale è fatto di solito?', es: '¿De qué material suele estar hecho?', pt: 'De que material geralmente é feito?', hi: 'यह आमतौर पर किस सामग्री से बना होता है?' },
    { en: 'Do you wear it indoors or outdoors?', fr: 'Le portez-vous à l\'intérieur ou à l\'extérieur ?', ar: 'هل ترتديه في الداخل أم في الخارج؟', de: 'Trägt man es drinnen oder draußen?', it: 'Lo indossi al chiuso o all\'aperto?', es: '¿Lo usas en interiores o exteriores?', pt: 'Você usa dentro ou fora de casa?', hi: 'क्या आप इसे घर के अंदर पहनते हैं या बाहर?' }
  ],
  'Home Objects': [
    { en: 'Which room is it usually found in?', fr: 'Dans quelle pièce le trouve-t-on généralement ?', ar: 'في أي غرفة يوجد عادة؟', de: 'In welchem Raum befindet es sich normalerweise?', it: 'In quale stanza si trova di solito?', es: '¿En qué habitación se encuentra normalmente?', pt: 'Em qual cômodo geralmente é encontrado?', hi: 'यह आमतौर पर किस कमरे में पाया जाता है?' },
    { en: 'Does it require electricity to work?', fr: 'A-t-il besoin d\'électricité pour fonctionner ?', ar: 'هل يحتاج إلى كهرباء ليعمل؟', de: 'Benötigt es Strom, um zu funktionieren?', it: 'Richiede elettricità per funzionare?', es: '¿Requiere electricidad para funcionar?', pt: 'Precisa de eletricidade para funcionar?', hi: 'क्या इसे काम करने के लिए बिजली की आवश्यकता होती है?' },
    { en: 'Is it used for sitting, sleeping, or something else?', fr: 'Est-il utilisé pour s\'asseoir, dormir ou autre chose ?', ar: 'هل يستخدم للجلوس أم النوم أم شيء آخر؟', de: 'Wird es zum Sitzen, Schlafen oder für etwas anderes verwendet?', it: 'È usato per sedersi, dormire o altro?', es: '¿Se usa para sentarse, dormir o algo más?', pt: 'É usado para sentar, dormir ou outra coisa?', hi: 'क्या इसका उपयोग बैठने, सोने या किसी अन्य चीज़ के लिए किया जाता है?' },
    { en: 'Is it heavy or easy to move?', fr: 'Est-il lourd ou facile à déplacer ?', ar: 'هل هو ثقيل أم يسهل تحريكه؟', de: 'Ist es schwer oder leicht zu bewegen?', it: 'È pesante o facile da spostare?', es: '¿Es pesado o fácil de mover?', pt: 'É pesado ou fácil de mover?', hi: 'क्या यह भारी है या इसे हिलाना आसान है?' },
    { en: 'What is its main purpose?', fr: 'Quel est son but principal ?', ar: 'ما هو الغرض الرئيسي منه؟', de: 'Was ist sein Hauptzweck?', it: 'Qual è il suo scopo principale?', es: '¿Cuál es su propósito principal?', pt: 'Qual é o seu propósito principal?', hi: 'इसका मुख्य उद्देश्य क्या है?' }
  ],
  'Movies': [
    { en: 'Is it animated or live-action?', fr: 'Est-ce un film d\'animation ou en prise de vues réelles ?', ar: 'هل هو رسوم متحركة أم تصوير حي؟', de: 'Ist es animiert oder Live-Action?', it: 'È animato o live-action?', es: '¿Es animada o de acción real?', pt: 'É animado ou live-action?', hi: 'क्या यह एनिमेटेड है या लाइव-एक्शन?' },
    { en: 'What genre is it (action, comedy, drama)?', fr: 'De quel genre s\'agit-il (action, comédie, drame) ?', ar: 'ما هو نوعه (أكشن، كوميديا، دراما)؟', de: 'Welches Genre ist es (Action, Komödie, Drama)?', it: 'Che genere è (azione, commedia, dramma)?', es: '¿Qué género es (acción, comedia, drama)?', pt: 'Qual é o gênero (ação, comédia, drama)?', hi: 'यह किस शैली का है (एक्शन, कॉमेडी, ड्रामा)?' },
    { en: 'Is it an old classic or a modern movie?', fr: 'Est-ce un vieux classique ou un film moderne ?', ar: 'هل هو فيلم كلاسيكي قديم أم حديث؟', de: 'Ist es ein alter Klassiker oder ein moderner Film?', it: 'È un vecchio classico o un film moderno?', es: '¿Es un clásico antiguo o una película moderna?', pt: 'É um clássico antigo ou um filme moderno?', hi: 'क्या यह एक पुरानी क्लासिक है या आधुनिक फिल्म?' },
    { en: 'Does it have superheroes or magic?', fr: 'Y a-t-il des super-héros ou de la magie ?', ar: 'هل يحتوي على أبطال خارقين أو سحر؟', de: 'Gibt es Superhelden oder Magie?', it: 'Ci sono supereroi o magia?', es: '¿Tiene superhéroes o magia?', pt: 'Tem super-heróis ou magia?', hi: 'क्या इसमें सुपरहीरो या जादू है?' },
    { en: 'Is it part of a series or a standalone movie?', fr: 'Fait-il partie d\'une série ou est-ce un film indépendant ?', ar: 'هل هو جزء من سلسلة أم فيلم مستقل؟', de: 'Ist es Teil einer Serie oder ein eigenständiger Film?', it: 'Fa parte di una serie o è un film a sé stante?', es: '¿Es parte de una serie o una película independiente?', pt: 'Faz parte de uma série ou é um filme independente?', hi: 'क्या यह किसी श्रृंखला का हिस्सा है या एक स्टैंडअलोन फिल्म है?' }
  ],
  'Countries': [
    { en: 'Which continent is it located in?', fr: 'Sur quel continent se trouve-t-il ?', ar: 'في أي قارة يقع؟', de: 'Auf welchem Kontinent liegt es?', it: 'In quale continente si trova?', es: '¿En qué continente se encuentra?', pt: 'Em qual continente está localizado?', hi: 'यह किस महाद्वीप में स्थित है?' },
    { en: 'Is it known for being hot or cold?', fr: 'Est-il connu pour être chaud ou froid ?', ar: 'هل هو معروف بكونه حارًا أم باردًا؟', de: 'Ist es dafür bekannt, heiß oder kalt zu sein?', it: 'È noto per essere caldo o freddo?', es: '¿Es conocido por ser caluroso o frío?', pt: 'É conhecido por ser quente ou frio?', hi: 'क्या यह गर्म या ठंडा होने के लिए जाना जाता है?' },
    { en: 'What language is primarily spoken there?', fr: 'Quelle langue y est principalement parlée ?', ar: 'ما هي اللغة التي يتم التحدث بها هناك بشكل أساسي؟', de: 'Welche Sprache wird dort hauptsächlich gesprochen?', it: 'Quale lingua si parla principalmente lì?', es: '¿Qué idioma se habla principalmente allí?', pt: 'Qual idioma é falado principalmente lá?', hi: 'वहाँ मुख्य रूप से कौन सी भाषा बोली जाती है?' },
    { en: 'Does it have famous landmarks?', fr: 'Possède-t-il des monuments célèbres ?', ar: 'هل يوجد به معالم شهيرة؟', de: 'Hat es berühmte Wahrzeichen?', it: 'Ha monumenti famosi?', es: '¿Tiene lugares emblemáticos famosos?', pt: 'Tem pontos turísticos famosos?', hi: 'क्या इसके प्रसिद्ध स्थल हैं?' },
    { en: 'Is it a large country by area?', fr: 'Est-ce un grand pays par sa superficie ?', ar: 'هل هو بلد كبير من حيث المساحة؟', de: 'Ist es ein flächenmäßig großes Land?', it: 'È un paese grande per superficie?', es: '¿Es un país grande por área?', pt: 'É um país grande em área?', hi: 'क्या यह क्षेत्रफल के हिसाब से एक बड़ा देश है?' }
  ]
};
